=== Channel-Cats-Scouting/1094-MyScout-Android/DataSet_Schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- DataSet Root Element -->
  <xs:element name="DataSet">
    <xs:complexType>
      <xs:sequence>
        
        <!-- Pre-Scout Data -->
        <xs:element name="PreScoutData">
          <xs:complexType>
            <xs:sequence minOccurs="0">
              <xs:element ref="Data" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        
        <!-- Round Data -->
        <xs:element name="RoundData">
          <xs:complexType>
            <xs:sequence>
              
              <!-- Autonomous Data-->
              <xs:element name="Autonomous" minOccurs="0">
                <xs:complexType>
                  <xs:sequence minOccurs="0">
                    <xs:element ref="Data" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
              <!-- Tele-Op Data -->
              <xs:element name="TeleOp" minOccurs="0">
                <xs:complexType>
                  <xs:sequence minOccurs="0">
                    <xs:element ref="Data" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      
      <!-- DataSet Attributes -->
      <xs:attribute name="name" use="optional" type="xs:string" />
      <xs:attribute name="version" use="required" type="xs:float" />
      <xs:attribute name="author" use="optional" type="xs:string" />
      
    </xs:complexType>
  </xs:element>

  <!-- Data Element -->
  <xs:element name="Data">
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="type" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Channel-Cats-Scouting/1094-MyScout-Android/2017Game.xml
<?xml version="1.0" encoding="utf-8" ?>
<DataSet name="FIRST Steamworks (2017)" version="1.0" author="1094 Channel Cats"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Channel-Cats-Scouting/1094-MyScout-Android/master/DataSet_Schema.xsd">
  <PreScoutData>
    <Data name="Can shoot at Low Goal" type="bool" />
    <Data name="Can shoot at High Goal" type="bool" />
    <Data name="Max Carried" type="int" />
  </PreScoutData>
  <RoundData>
    <Autonomous>
      <Data name="Low Goals" type="int" />
      <Data name="High Goals" type="int" />
      <Data name="Got Gear" type="bool" />
      <Data name="Crossed Line" type="bool" />
    </Autonomous>
    <TeleOp>
      <Data name="Low Goals" type="int" />
      <Data name="High Goals" type="int" />
      <Data name="Gears Delivered" type="int" />
      <Data name="Rope Climbed" type="bool" />
    </TeleOp>
  </RoundData>
</DataSet>
